development:
  adapter: mysql2
  database: eventstreams2_development
  username: root
  password: 
  pool: 5
  host: 127.0.0.1

edge:
  adapter: mysql2
  database: eventstreams_edge
  username: root
  password: mrsafe
  pool: 5
  host: 127.0.0.1

staging:
  adapter: mysql2
  database: eventstreams_staging
  username: root
  password: mrsafe
  pool: 5
  host: 127.0.0.1

production:
  adapter: mysql2
  database: eventstreams_production
  username: root
  password: mrsafe
  pool: 5
  host: 127.0.0.1

test: &test
  adapter: mysql2
  database: eventstreams2_test
  username: root
  password: 
  pool: 5
  host: 127.0.0.1

cucumber:
  <<: *test
  
# production:
#   adapter: sqlite3
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000
  